name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ feature/change-addr-to-bech32 ]
env:
  GO111MODULE: on
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    
    
   # - name: Build
   #   run: make platon

    #- name: golangci-lint
     # run: |
     #   go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.27.0
     #   golangci-lint run --no-config  --issues-exit-code=0 --timeout=30m --tests=false --skip-dirs="tests" --skip-dirs-use-default="true" --disable-all --enable=govet  --enable=misspell --enable=goconst --enable=gofmt --enable=goimports  --enable=gosec  --enable=unconvert  --enable=unparam  --enable=funlen 
    
    - name: golangci-lint
      uses: reviewdog/action-golangci-lint@v1
    
    - name: Test
      run: go test -tags=test -covermode=count -coverprofile=coverage.out  `go list ./...|grep -v life|grep -v swarm|grep -v tests|grep -v bn256|grep -v mobile`
      
    

